name: degree_app
description: Degree App
version: 0.0.1+3
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.4

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  hydrated_bloc: ^8.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  meta: ^1.8.0
  mocktail: ^0.3.0
  path_provider: ^2.0.11
  provider: ^6.0.4
  responsive_sizer: ^3.1.1

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo/
    - assets/fonts/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Semibold.ttf
          weight: 600
