name: task_service
description: Task RESTful API service
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  dotenv: ^4.0.1
  path: ^1.8.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  postgres: ^2.5.2
  dart_jsonwebtoken: ^2.4.2
  dio: ^4.0.6
  mime: ^1.0.2
  http_parser: ^4.0.2
  crypto: ^3.0.2
  shelf_cors_headers: ^0.1.4
  translit: ^2.0.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
