version: '3.8'

services:

  degree_auth_service:
    container_name: auth_service
    build: ./auth_service
    expose:
      - ${AUTH_SERVICE_PORT}
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
      - AUTH_SERVICE_HOST=${AUTH_SERVICE_HOST}
      - AUTH_DATABASE_HOST=${AUTH_DATABASE_HOST}
      - AUTH_DATABASE_PORT=${AUTH_DATABASE_PORT}
      - AUTH_DATABASE_NAME=${AUTH_DATABASE_NAME}
      - AUTH_DATABASE_USERNAME=${AUTH_DATABASE_USERNAME}
      - AUTH_DATABASE_PASSWORD=${AUTH_DATABASE_PASSWORD}
    depends_on:
      - degree_auth_db
    networks:
      - degree_network

  degree_auth_db:
    container_name: auth_db
    image: postgres:14.5-alpine
    ports:
      - "${AUTH_DATABASE_PORT}:${AUTH_DATABASE_PORT}"
    environment:
      POSTGRES_USER: ${AUTH_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_DATABASE_PASSWORD}
      POSTGRES_DB: ${AUTH_DATABASE_NAME}
    command: -p ${AUTH_DATABASE_PORT}
    volumes:
      - degree_auth_db:/var/lib/postgresql/data
      - ./auth_db/:/docker-entrypoint-initdb.d
    networks:
      - degree_network

  degree_schedule_db:
    container_name: schedule_db
    image: postgres:14.5-alpine
    ports:
      - "${SCHEDULE_DATABASE_PORT}:${SCHEDULE_DATABASE_PORT}"
    environment:
      POSTGRES_USER: ${SCHEDULE_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${SCHEDULE_DATABASE_PASSWORD}
      POSTGRES_DB: ${SCHEDULE_DATABASE_NAME}
    command: -p ${SCHEDULE_DATABASE_PORT}
    volumes:
      - degree_schedule_db:/var/lib/postgresql/data
      - ./schedule_db/:/docker-entrypoint-initdb.d
    networks:
      - degree_network

volumes:
  degree_auth_db: {}
  degree_schedule_db: {}

networks:
  degree_network:
    driver: bridge
