name: degree_app
description: DegreeApp.

publish_to: "none"

version: 0.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  injectable: ^1.5.3
  get_it: ^7.2.0
  dio: ^4.0.6
  hive: ^2.2.3
  flutter_bloc: ^8.1.1
  freezed: ^2.1.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^1.5.4
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
