-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.tags
(
    tag_id serial NOT NULL,
    tag_name character varying NOT NULL,
    PRIMARY KEY (tag_id)
);

CREATE TABLE IF NOT EXISTS public.task_files
(
    file_id serial NOT NULL,
    user_id serial NOT NULL,
    file_name character varying NOT NULL,
    url character varying NOT NULL,
    size serial NOT NULL,
    created_at date NOT NULL,
    CONSTRAINT pk_task_files PRIMARY KEY (file_id)
);

CREATE TABLE IF NOT EXISTS public.tasks
(
    task_id serial NOT NULL,
    subject_id serial NOT NULL,
    teacher_id serial NOT NULL,
    student_id bigint,
    group_id bigint,
    subgroup_id bigint,
    content text NOT NULL,
    deadline_type character varying NOT NULL,
    deadline date,
    PRIMARY KEY (task_id)
);

CREATE TABLE IF NOT EXISTS public.tasks_files
(
    task_id serial NOT NULL,
    file_id serial NOT NULL,
    PRIMARY KEY (task_id, file_id)
);

CREATE TABLE IF NOT EXISTS public.tasks_tags
(
    task_id serial NOT NULL,
    tag_id serial NOT NULL,
    PRIMARY KEY (task_id, tag_id)
);

CREATE TABLE IF NOT EXISTS public.students_complete
(
    student_id serial NOT NULL,
    task_id serial NOT NULL,
    is_complete boolean NOT NULL,
    PRIMARY KEY (student_id, task_id)
);

ALTER TABLE IF EXISTS public.tasks_files
    ADD CONSTRAINT fk_tasks_files_task_id FOREIGN KEY (task_id)
    REFERENCES public.tasks (task_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.tasks_files
    ADD CONSTRAINT fk_tasks_files_file_id FOREIGN KEY (file_id)
    REFERENCES public.task_files (file_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.tasks_tags
    ADD CONSTRAINT fk_tasks_tags_task_id FOREIGN KEY (task_id)
    REFERENCES public.tasks (task_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.tasks_tags
    ADD CONSTRAINT fk_tasks_tags_tag_id FOREIGN KEY (tag_id)
    REFERENCES public.tags (tag_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.students_complete
    ADD FOREIGN KEY (task_id)
    REFERENCES public.tasks (task_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;