export 'package:degree_app/admin/cubit/action_panel_cubit.dart';
export 'package:degree_app/admin/data/users_mock.dart';
export 'package:degree_app/admin/model/user_model.dart';
export 'package:degree_app/admin_subjects/admin_subjects.dart';
export 'package:degree_app/degree_ui/degree_ui.dart';
export 'package:equatable/equatable.dart';
export 'package:flutter_bloc/flutter_bloc.dart';
export 'package:json_annotation/json_annotation.dart';

export 'src/cubit/action_panel/student_panel_cubit.dart';
export 'src/cubit/page/students_page_cubit.dart';
export 'src/data/mock_student_repository.dart';
export 'src/model/student_model.dart';
export 'src/repository/student_repository.dart';
export 'src/view/action_panel/add_student_panel.dart';
export 'src/view/action_panel/edit_student_panel.dart';
export 'src/view/action_panel/info_student_panel.dart';
export 'src/view/action_panel/loading_student_panel.dart';
export 'src/view/page/teacher_page.dart';
