name: schedule_service
description: Schedule RESTful API service
version: 1.0.0

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  dotenv: ^4.0.1
  path: ^1.8.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  postgres: ^2.5.2
  dart_jsonwebtoken: ^2.4.2
  dio: ^4.0.6
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
