-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    username character varying(64),
    hashed_password character varying,
    salt character varying,
    CONSTRAINT pk_user_id PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.tokens
(
    token_id serial NOT NULL,
    user_id serial NOT NULL,
    refresh_token character varying NOT NULL,
    expired_time date NOT NULL,
    CONSTRAINT pk_token_id PRIMARY KEY (token_id)
);

ALTER TABLE IF EXISTS public.tokens
    ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;